"""
Report generation handler — TXT, HTML, PDF.
"""
import io
import os
import logging
from datetime import datetime
from telegram import Update
from telegram.ext import ContextTypes
from database.db import get_user_history
from middleware.ban_checker import ban_checker_middleware

logger = logging.getLogger(__name__)


def generate_txt_report(history: list, user_name: str) -> bytes:
    lines = [
        "=" * 60,
        "OSINT BOT - SEARCH HISTORY REPORT",
        f"User: {user_name}",
        f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "=" * 60,
        "",
        "LEGAL NOTICE: This report contains publicly available data only.",
        "Do not use for illegal purposes.",
        "",
        "-" * 60,
        "SEARCH HISTORY",
        "-" * 60,
        ""
    ]
    for i, h in enumerate(history, 1):
        lines.append(f"{i}. [{h['query_type'].upper()}] {h['query_value']}")
        lines.append(f"   Result: {h['result_summary']}")
        lines.append(f"   Date:   {h['created_at']}")
        lines.append("")
    lines.append("=" * 60)
    lines.append("END OF REPORT")
    return "\n".join(lines).encode("utf-8")


def generate_html_report(history: list, user_name: str) -> bytes:
    rows = ""
    for i, h in enumerate(history, 1):
        rows += f"""
        <tr>
            <td>{i}</td>
            <td><span class="badge">{h['query_type'].upper()}</span></td>
            <td>{h['query_value']}</td>
            <td>{h['result_summary']}</td>
            <td>{h['created_at']}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>OSINT Report - {user_name}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }}
  .header {{ background: linear-gradient(135deg, #1e3a5f, #1a1a2e); border: 1px solid #334155; border-radius: 12px; padding: 2rem; margin-bottom: 2rem; }}
  h1 {{ font-size: 1.8rem; color: #60a5fa; margin-bottom: 0.5rem; }}
  .meta {{ color: #94a3b8; font-size: 0.9rem; }}
  .notice {{ background: #1e293b; border-left: 4px solid #f59e0b; padding: 1rem 1.5rem; border-radius: 0 8px 8px 0; margin-bottom: 2rem; color: #fbbf24; }}
  table {{ width: 100%; border-collapse: collapse; background: #1e293b; border-radius: 12px; overflow: hidden; }}
  th {{ background: #1e3a5f; padding: 1rem; text-align: left; color: #60a5fa; font-weight: 600; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; }}
  td {{ padding: 0.85rem 1rem; border-bottom: 1px solid #334155; font-size: 0.9rem; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover td {{ background: #243347; }}
  .badge {{ background: #1e3a5f; color: #60a5fa; padding: 0.2rem 0.6rem; border-radius: 999px; font-size: 0.75rem; font-weight: 600; border: 1px solid #3b82f6; }}
  .footer {{ text-align: center; margin-top: 2rem; color: #475569; font-size: 0.8rem; }}
</style>
</head>
<body>
<div class="header">
  <h1>🔍 OSINT Bot — Search Report</h1>
  <div class="meta">
    <strong>User:</strong> {user_name} &nbsp;|&nbsp;
    <strong>Generated:</strong> {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')} &nbsp;|&nbsp;
    <strong>Searches:</strong> {len(history)}
  </div>
</div>
<div class="notice">
  ⚠️ <strong>Legal Notice:</strong> This report contains publicly available data only. 
  Use responsibly and in compliance with applicable laws.
</div>
<table>
  <thead>
    <tr>
      <th>#</th><th>Type</th><th>Query</th><th>Result Summary</th><th>Date (UTC)</th>
    </tr>
  </thead>
  <tbody>{rows}</tbody>
</table>
<div class="footer">Generated by OSINT Bot &mdash; Public data only &mdash; {datetime.utcnow().year}</div>
</body>
</html>"""
    return html.encode("utf-8")


def generate_pdf_report(history: list, user_name: str) -> bytes:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                                topMargin=2*cm, bottomMargin=2*cm,
                                leftMargin=2*cm, rightMargin=2*cm)
        styles = getSampleStyleSheet()
        story = []

        title_style = ParagraphStyle("title", parent=styles["Title"],
                                     textColor=colors.HexColor("#1e3a5f"),
                                     fontSize=18, spaceAfter=6)
        meta_style = ParagraphStyle("meta", parent=styles["Normal"],
                                    textColor=colors.grey, fontSize=9, spaceAfter=4)
        notice_style = ParagraphStyle("notice", parent=styles["Normal"],
                                      textColor=colors.HexColor("#b45309"),
                                      fontSize=8, spaceAfter=12,
                                      backColor=colors.HexColor("#fef3c7"),
                                      leftIndent=10, rightIndent=10)

        story.append(Paragraph("🔍 OSINT Bot — Search Report", title_style))
        story.append(Paragraph(
            f"User: {user_name} | Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} | Searches: {len(history)}",
            meta_style
        ))
        story.append(Spacer(1, 0.3*cm))
        story.append(Paragraph(
            "⚠️ LEGAL NOTICE: This report contains publicly available data only. "
            "Use responsibly and in compliance with applicable laws.",
            notice_style
        ))
        story.append(Spacer(1, 0.5*cm))

        table_data = [["#", "Type", "Query", "Summary", "Date"]]
        for i, h in enumerate(history, 1):
            table_data.append([
                str(i),
                h["query_type"].upper(),
                h["query_value"][:30],
                h["result_summary"][:40] if h["result_summary"] else "",
                h["created_at"][:16]
            ])

        table = Table(table_data, colWidths=[1*cm, 2.5*cm, 4*cm, 6*cm, 3.5*cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a5f")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("FONTSIZE", (0, 1), (-1, -1), 7.5),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("PADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(table)

        doc.build(story)
        buffer.seek(0)
        return buffer.read()
    except ImportError:
        logger.warning("reportlab not installed, returning txt fallback")
        return generate_txt_report(history, user_name)


@ban_checker_middleware
async def generate_report(update: Update, context: ContextTypes.DEFAULT_TYPE):
    fmt = context.args[0].lower() if context.args else "txt"
    if fmt not in ("txt", "html", "pdf"):
        await update.message.reply_text(
            "Usage: /report `<format>`\n\nFormats: `txt`, `html`, `pdf`",
            parse_mode="Markdown"
        )
        return

    user = update.effective_user
    history = get_user_history(user.id, limit=50)

    if not history:
        await update.message.reply_text(
            "📭 No search history found. Run some searches first!"
        )
        return

    await update.message.reply_text(f"📊 Generating *{fmt.upper()}* report...", parse_mode="Markdown")

    user_name = user.username or user.first_name or str(user.id)

    if fmt == "txt":
        data = generate_txt_report(history, user_name)
        await update.message.reply_document(
            document=io.BytesIO(data),
            filename=f"osint_report_{user_name}_{datetime.utcnow().strftime('%Y%m%d_%H%M')}.txt",
            caption="📄 Your OSINT search history report (TXT)"
        )
    elif fmt == "html":
        data = generate_html_report(history, user_name)
        await update.message.reply_document(
            document=io.BytesIO(data),
            filename=f"osint_report_{user_name}_{datetime.utcnow().strftime('%Y%m%d_%H%M')}.html",
            caption="🌐 Your OSINT search history report (HTML)"
        )
    elif fmt == "pdf":
        data = generate_pdf_report(history, user_name)
        await update.message.reply_document(
            document=io.BytesIO(data),
            filename=f"osint_report_{user_name}_{datetime.utcnow().strftime('%Y%m%d_%H%M')}.pdf",
            caption="📑 Your OSINT search history report (PDF)"
        )
